# Generated by Django 5.0.3 on 2024-04-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_jobs_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpofile',
            name='saved_jobs',
            field=models.ManyToManyField(null=True, related_name='saved', to='myapp.jobs'),
        ),
    ]
