# Generated by Django 5.0.3 on 2024-04-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_studentpofile_saved_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='applied_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
