# Generated by Django 5.0.3 on 2024-04-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_applications_applied_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('processing', 'processing'), ('shortlisted', 'shortlisted')], default='pending', max_length=200),
        ),
    ]
